services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - API_URL=https://candidate-testing.api.royal-apps.io
      - NODE_ENV=development
    stdin_open: true
    tty: true
